// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.IntakeSubsystem;

public class AutoEject extends CommandBase {
    private long startingTime;

    private final IntakeSubsystem m_intake;

    public AutoEject(IntakeSubsystem subsystem) {

        m_intake = subsystem;
        addRequirements(m_intake);

    }

    @Override
    public void initialize() {
        startingTime = System.currentTimeMillis();

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_intake.set_speed(0.53);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_intake.set_speed(0);
    }

    // Returns true when the command should end.

    private final int MaxTime = 1000;

    @Override
    public boolean isFinished() {
        long elapsedTime = System.currentTimeMillis() - startingTime;
        return elapsedTime > MaxTime ? true : false;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}